---
- lineinfile: state=present dest=/etc/iptables/iptables.rules line="-A POSTROUTING -o {{ snat_dev }} -j SNAT --to-source {{ snat_ip4 }}" insertafter="^\*nat$"
- template: src=03-public-ip.network.j2 dest=/etc/systemd/network/03-public-ip.network
- template: src=bird_ffrhein.conf.j2 dest=/etc/bird/bird_ffrhein.conf
  tags:
    - bird
